### ISSUE TITLE
base16 script overrides .Xresources

### ISSUE THREAD

**Issue by Debonnys** [hamvocke/dotfiles#1]
Hello,

I'm trying to use some of your configurations and one of the issues I have is that when I use the [base16 script](https://github.com/hamvocke/dotfiles/blob/master/zsh/.zshrc#L54) for the colors it overrides the settings in my .Xresources file.

I don't mind overriding the color values there but I want a bigger font size in xterm and the base16 always reverts to the small default size. Do you know how I can fix this?

**Comment by hamvocke** [comment]
Looks like base16-shell could be a little too much for you. There's a dedicated [base16-Xresources](https://github.com/chriskempson/base16-xresources) project that you could fetch your favourite colour scheme from. Maybe using that instead of the snippet in my .zshrc helps with your situation?

**Comment by Debonnys** [comment]
That worked perfectly, thanks a lot!
