### ISSUE TITLE
Updating tmux config README

### ISSUE THREAD

**Issue by ScottA38** [hamvocke/dotfiles#3]
The readme for tmux notes that you should use the 'reattach-to-user-namespace' package, however I found [this](https://github.com/tmux-plugins/tmux-sensible/issues/42) reference which in up-to-date OSX versions should fix the system copy buffer issue (it did for me)

**Comment by hamvocke** [comment]
You're right. Good to see that this works without this workaround now. I removed the reference in the README. Thanks for your help!
