### ISSUE TITLE
Color in TMUX Example

### ISSUE THREAD

**Issue by LockeAG** [hamvocke/dotfiles#4]
Hi , thank for dotfiles, Rock Big time..

I would like to know the configuration of colors that you have in the README example, looks quite good.

Thanks

**Comment by hamvocke** [comment]
You should be able to re-create the colors from the `tmux.conf` as it was back when I added the screenshot. [This](https://github.com/hamvocke/dotfiles/blob/dc616cc2e01bee191737830b627644812ffd8525/tmux.conf#L63-L160) is the config part you're looking for. It's a bit messy and might need some cleanup to work with current versions of tmux. Basically, you should be good to take the color values from there and put it into the current version of the `tmux.conf` in the repo.
